### ISSUE TITLE
overlay only works once

### ISSUE THREAD

**Issue by stephenmathieson** [component/dialog#21]
i've got a modal dialog which will be displayed any number of times (e.g. possibly more than once).  seeing weird behaviour with the background "overlay" due to [this](https://github.com/component/dialog/blob/master/index.js#L186) line.  any reason we don't just call `overlay.remove()` instead of setting it to `null`?

**Comment by pirxpilot** [comment]
Looks like a bug to me: `hide` calls `hideOverlay`, which hides/remove overlay and resets `this._overlay` - I think this line can be safely removed.
