### ISSUE TITLE
Update npm version

### ISSUE THREAD

**Issue by dfcreative** [component/dialog#25]
Could you please publish new npm version?

**Comment by dfcreative** [comment]
@juliangruber @travisjeffery @rauchg sorry for disturbing, but I'm afraid this issue can be left unnoticed )

**Comment by juliangruber** [comment]
`dialog-component@0.4.0` has been published :)

**Comment by dfcreative** [comment]
@juliangruber hi) Sorry for disturbing, but could you publish a patch to npm? I'd appreciate it much.

**Comment by dfcreative** [comment]
@juliangruber or could you add me to collaborators list in the npm repo? I won't bother you anymore then )

**Comment by juliangruber** [comment]
@jonathanong i think you have a script fo this?

**Comment by jonathanong** [comment]
https://github.com/repo-utils/npm-org-rights

**Comment by juliangruber** [comment]
@dfcreative i gave you access to all the component repos that i have access to, including this one

**Comment by dfcreative** [comment]
Wow, that's just wonderful! Thanks a lot.
